// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQtiF2ck4RHwYST34caTj1eAel10iIDZk',
    appId: '1:544103993224:web:d34d746a59ff1b0206b43d',
    messagingSenderId: '544103993224',
    projectId: 'occupai-e5376',
    authDomain: 'occupai-e5376.firebaseapp.com',
    storageBucket: 'occupai-e5376.firebasestorage.app',
    measurementId: 'G-QMRBWP6LS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnSEeIcmMYNmYpaKyESGN7sOhTaUwXMVI',
    appId: '1:544103993224:android:7035cd8a7faa51bf06b43d',
    messagingSenderId: '544103993224',
    projectId: 'occupai-e5376',
    storageBucket: 'occupai-e5376.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXDPeu3jqfuHLT6c-IEt1xcyi63oJyxaQ',
    appId: '1:544103993224:ios:2acc8451c5c7e19106b43d',
    messagingSenderId: '544103993224',
    projectId: 'occupai-e5376',
    storageBucket: 'occupai-e5376.firebasestorage.app',
    iosBundleId: 'com.example.ki4cDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXDPeu3jqfuHLT6c-IEt1xcyi63oJyxaQ',
    appId: '1:544103993224:ios:2acc8451c5c7e19106b43d',
    messagingSenderId: '544103993224',
    projectId: 'occupai-e5376',
    storageBucket: 'occupai-e5376.firebasestorage.app',
    iosBundleId: 'com.example.ki4cDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQtiF2ck4RHwYST34caTj1eAel10iIDZk',
    appId: '1:544103993224:web:e5d397905e72424406b43d',
    messagingSenderId: '544103993224',
    projectId: 'occupai-e5376',
    authDomain: 'occupai-e5376.firebaseapp.com',
    storageBucket: 'occupai-e5376.firebasestorage.app',
    measurementId: 'G-7P813G2BS2',
  );
}
